"""initial schema

Revision ID: cf8fba1aebfa
Revises: 
Create Date: 2026-07-30 12:26:30.302584
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cf8fba1aebfa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('arxiv_id_base', sa.String(length=50), nullable=False),
    sa.Column('arxiv_version', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_zh', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('summary_zh', sa.Text(), nullable=True),
    sa.Column('one_line_zh', sa.Text(), nullable=True),
    sa.Column('primary_category', sa.String(length=100), nullable=True),
    sa.Column('secondary_categories', sa.JSON(), nullable=True),
    sa.Column('arxiv_primary_category', sa.String(length=50), nullable=True),
    sa.Column('arxiv_categories', sa.JSON(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('institutions', sa.JSON(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('paper_status', sa.String(length=20), nullable=False),
    sa.Column('source_status', sa.String(length=50), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('html_url', sa.Text(), nullable=True),
    sa.Column('arxiv_url', sa.Text(), nullable=True),
    sa.Column('project_url', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('journal_reference', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('has_code', sa.Boolean(), nullable=False),
    sa.Column('has_model', sa.Boolean(), nullable=False),
    sa.Column('has_dataset', sa.Boolean(), nullable=False),
    sa.Column('has_demo', sa.Boolean(), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_source', sa.String(length=50), nullable=True),
    sa.Column('editorial_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_arxiv_id_base'), 'papers', ['arxiv_id_base'], unique=True)
    op.create_index(op.f('ix_papers_editorial_status'), 'papers', ['editorial_status'], unique=False)
    op.create_index(op.f('ix_papers_paper_status'), 'papers', ['paper_status'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_from', sa.String(length=20), nullable=True),
    sa.Column('date_to', sa.String(length=20), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('unique_count', sa.Integer(), nullable=False),
    sa.Column('new_paper_count', sa.Integer(), nullable=False),
    sa.Column('new_version_count', sa.Integer(), nullable=False),
    sa.Column('hf_match_count', sa.Integer(), nullable=False),
    sa.Column('s2_match_count', sa.Integer(), nullable=False),
    sa.Column('github_match_count', sa.Integer(), nullable=False),
    sa.Column('pending_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_zh', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('tag_type', sa.String(length=20), nullable=False),
    sa.Column('primary_domain', sa.String(length=100), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('github_repositories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('repo', sa.String(length=200), nullable=False),
    sa.Column('repository_url', sa.Text(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('forks', sa.Integer(), nullable=True),
    sa.Column('open_issues', sa.Integer(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=True),
    sa.Column('created_at_remote', sa.DateTime(), nullable=True),
    sa.Column('updated_at_remote', sa.DateTime(), nullable=True),
    sa.Column('pushed_at', sa.DateTime(), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('match_source', sa.String(length=50), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_repositories_paper_id'), 'github_repositories', ['paper_id'], unique=False)
    op.create_table('metric_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_snapshots_paper_id'), 'metric_snapshots', ['paper_id'], unique=False)
    op.create_table('paper_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('tag_source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_tags_paper_id'), 'paper_tags', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_tags_tag_id'), 'paper_tags', ['tag_id'], unique=False)
    op.create_table('source_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_file_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_records_paper_id'), 'source_records', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_records_paper_id'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_paper_tags_tag_id'), table_name='paper_tags')
    op.drop_index(op.f('ix_paper_tags_paper_id'), table_name='paper_tags')
    op.drop_table('paper_tags')
    op.drop_index(op.f('ix_metric_snapshots_paper_id'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index(op.f('ix_github_repositories_paper_id'), table_name='github_repositories')
    op.drop_table('github_repositories')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_papers_paper_status'), table_name='papers')
    op.drop_index(op.f('ix_papers_editorial_status'), table_name='papers')
    op.drop_index(op.f('ix_papers_arxiv_id_base'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
